version: "3"
networks:
  node-clean:
    driver: bridge
services:
  mysql:
    image: mysql
    container_name: node-clean-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ../mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodejs
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    command: mysqld --log-bin-trust-function-creators=1
    networks:
      - node-clean
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: node-clean-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: LNIBsCP9Gj7xF4d3
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 104857600
      MEMORY_LIMIT: 2G
      # MAX_EXECUTION_TIME: 600
    ports:
      - "8102:80"
    networks:
      - node-clean
  redis:
    image: redis
    container_name: node-clean-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "6379:6379"
    networks:
      - node-clean
  redisinsight:
    image: redislabs/redisinsight
    container_name: node-clean-redisinsight
    restart: unless-stopped
    volumes:
      - ../redis:/var/lib/redis
    ports:
      - "8103:8001"
    networks:
      - node-clean
  api:
    container_name: node-clean-api
    image: node:19
    working_dir: /usr/src/node-clean-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/node-clean-api/dist/
      - ./package.json:/usr/src/node-clean-api/package.json
    ports:
      - "8080:8080"
    links:
      - redis
      - mysql